# Generated by Django 3.2.16 on 2022-10-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['created_on']},
        ),
    ]
